steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration Release --output ./bin/Release/net8.0/publish'
    zipAfterPublish: False

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: build
    Dockerfile: '**/Dockerfile'
    buildContext: '$(Build.Repository.LocalPath)'